apiVersion: release-notes/v2
kind: feature
area: traffic-management
issue: []
releaseNotes:
- |
  **Added** added the "service_protocol" field to the sidecar ingress listener configuration to allow specifying that the downgraded protocol should be http2
upgradeNotes: []
docs: []
securityNotes: []